### ISSUE TITLE
om variable interpolation fails if a file is passed as an individual var

### ISSUE THREAD

**Issue by iplay88keys** [pivotal-cf/om#472]
We got a panic when running om interpolation for a command. Presumably, it was due to the fact that we passed files in for individual var flags - using `-v` instead of `--vars-file`. This may be a problem in combination with the use of a `../` path.

Here's the command we were using (with files otherwise valid): 

```
$ om -e /tmp/env.yml configure-director --config /tmp/director.yml -v ../vars/director.yml -v vars/director.yml
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/pivotal-cf/om/interpolate.readCommandLineVars(0xc000456e40, 0x2, 0x2, 0xc000450420)
	/tmp/build/80754af9/om/interpolate/execute.go:132 +0x4e2
github.com/pivotal-cf/om/interpolate.Execute(0x7ffeefbff6af, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000456e40, 0x2, ...)
	/tmp/build/80754af9/om/interpolate/execute.go:91 +0x343
github.com/pivotal-cf/om/commands.ConfigureDirector.interpolateConfig(0x1b252b8, 0x1d5e340, 0xc000476550, 0x1d48960, 0xc0000abe50, 0x0, 0x7ffeefbff6af, 0x11, 0x0, 0x0, ...)
	/tmp/build/80754af9/om/commands/configure_director.go:151 +0x167
github.com/pivotal-cf/om/commands.ConfigureDirector.Execute(0x1b252b8, 0x1d5e340, 0xc000476550, 0x1d48960, 0xc0000abe50, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/80754af9/om/commands/configure_director.go:92 +0x207
github.com/pivotal-cf/jhanda.CommandSet.Execute(0xc0004512f0, 0x7ffeefbff693, 0x12, 0xc0000300e0, 0x6, 0x6, 0x6, 0x0)
	/go/pkg/mod/github.com/pivotal-cf/jhanda@v0.0.0-20191113141013-9cb1997202c0/command_set.go:25 +0x133
main.main()
	/tmp/build/80754af9/om/main.go:213 +0x6061
```

We may need to do some followup to figure out exactly why there's a panic instead of a good error here.

**Comment by kcboyle** [comment]
Added verification check to ensure that any passed in var follows the format:
```
key=value
```
any other attempts will fail with a nice error message.

this will be released in `om 4.7.0`
