### ISSUE TITLE
Random segmentation fault when downloading products from pivnet

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/om#550]
We have been randomly experiencing seg faults when downloading large products like cloud foundry from pivnet.  OM is running in a container backed by the binary buildpack.  The container is given 2G of memory and 15G of disk in order to download the product.  The failure typically results in log lines like the following:

```
   2021-06-14T16:56:05.45-0500 [APP/TASK/e7fabc94/0] ERR  8.27 GiB / 10.87 GiB [===============================>---------]  76.07% 00m22s
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR  8.27 GiB / 10.87 GiB [===============================>---------]  76.07% 00m20spanic: runtime error: invalid memory address or nil pointer dereference
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8d8a5a]
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR goroutine 97 [running]:
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR github.com/pivotal-cf/go-pivnet/v6/download.Client.retryableRequest(0x23ab760, 0xc0001ba060, 0x23acba0, 0x3103990, 0x23db4a0, 0xc000558160, 0x23ba8a0, 0xc0004cf240, 0x12a05f200, 0xc000a0c480, ...)
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR        /go/pkg/mod/github.com/pivotal-cf/go-pivnet/v6@v6.0.2/download/downloader.go:208 +0x3fa
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR        /go/pkg/mod/github.com/pivotal-cf/go-pivnet/v6@v6.0.2/download/downloader.go:130 +0x105
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR        /go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR created by golang.org/x/sync/errgroup.(*Group).Go
   2021-06-14T16:56:06.44-0500 [APP/TASK/e7fabc94/0] ERR        /go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66
   2021-06-14T16:56:06.54-0500 [APP/TASK/e7fabc94/0] OUT Exit status 2
```

Rerunning the container to download the product results in a successful run.

OM version 7.2.0

**Comment by jaristiz** [comment]
Hi @xyloman ,

Are you still seeing this issue, if so, can you try updating to the latest version and provide us with more information?

**Comment by jaristiz** [comment]
As no new information has been provided I can count this issue as closed.

**Comment by xyloman** [comment]
@jaristiz sorry for the delayed response I was on PTO.  Basically the issue was we were running in a container with only 1 GB of memory downloading a file that was 10+ gb from tanzu network.  By giving the container more memory say 2 GB or 4 GB in the case of the 10+gb file we were not able to reproduce this issue with the current and previous versions of the cli.  In comparison when we run this same cli in a concourse job we do not experience the exception because we did not have container limits enabled in concourse on the job containers so they had fully access to the memory of the worker node.  So the question would be is this expected behavior?
