### ISSUE TITLE
getting error message Error: cannot load such file -- io/console when tapping pivotal-cf/om

### ISSUE THREAD

**Issue by sbogar-shs** [pivotal-cf/om#580]
==> amazon-ebs.concourse_host: ==> Tapping pivotal-cf/om
==> amazon-ebs.concourse_host: Cloning into '\''/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/pivotal-cf/homebrew-om'\''...
==> amazon-ebs.concourse_host: Tapped 3 commands and 1 formula (1,061 files, 23.1MB).
==> amazon-ebs.concourse_host: Error: cannot load such file -- io/console
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/sandbox.rb:5:in `require'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/sandbox.rb:5:in `<top (required)>'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:12:in `require'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:12:in `<top (required)>'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:8:in `require'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:8:in `<top (required)>'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:92:in `require'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:92:in `require?'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/commands.rb:35:in `valid_internal_cmd?'\''
==> amazon-ebs.concourse_host: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'\''

I have tried adding 'gem install io-console' earlier in the build but it did not seem to have an effect.

This appears to be a fairly recent behavior.  This worked in October, 2021.

**Comment by sbogar-shs** [comment]
The issue was due to the use of ruby 2.6.   Once we updated to ruby 3.0 (on amazon linux 2 / yum distro) the installation issue was resolved.
