### ISSUE TITLE
Can't unset `director_hostname`

### ISSUE THREAD

**Issue by BooleanCat** [pivotal-cf/om#70]
I can run `{opsman stuff} -k configure-bosh --director-configuration '{"director_hostname":"foo"}'` successfully.

When I try to unset this field with `{opsman stuff} -k configure-bosh --director-configuration '{"director_hostname":""}'` I see the following failure:

```
opsman -k configure-bosh --director-configuration '{"director_hostname":""}'
configuring director options for bosh tile
could not execute "configure-bosh": tile failed to configure: request failed: unexpected response:
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Tue, 09 May 2017 16:41:18 GMT
Server: nginx/1.4.6 (Ubuntu)
Set-Cookie: _web_session=WXRUbWRsWU9TUGZSd00yUWdGTXdEb2Q3WVdZSmRMZFNXd2NiMTZRNFRWbHQzdC8xS1ZGQnZpd08ramc1T1N0QUFoT09pWnR5akFkbTZiSDloT2pRVFkxUTZESlNKd3psbmJRRUtWMFRCcFY0anJsVVJyeFZ0ZG40WDF4aVRoUzRkck1TYWhsa3Z2ci9YQmlSWjZvcG5RPT0tLVJOV0RXUEZHOVcySjlVdjRMWnBZUkE9PQ%3D%3D--8181ea0de2d98b96334e43fe8c33b288d4075b07; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 6acf8a34-95b2-4036-b9e6-69e4e9107231
X-Runtime: 1.144350
X-Xss-Protection: 1; mode=block

2d40
<!DOCTYPE html>
<html>
<head>
<meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
<meta content='0' http-equiv='expires'>
<meta content='text/javascript' http-equiv='Content-Script-Type'>
<meta content='text/css' http-equiv='Content-Style-Type'>
<meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
<link href='/favicon.png' rel='icon' type='image/png'>
<title>Ops Manager</title>
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="jDxNA+/TxV2hU06CWWuGKywot8rByLnFDTegolprsfUkwm7HVRXr77gQE/ItaFTN6c0F5ERnKcDqVOVjIM2l5g==" />
<link rel="stylesheet" media="screen" href="/assets/application-2c29ca884d37864467d5334e1c4883aa2e3c58c564e77a00d4c3b12fe66bb4b0.css" />
<script src="/assets/application-3f515a698587bf8a738bf1f5f944a2c08fed10676595d017d6de9b2eb2cbd9fb.js"></script>


</head>
<body class='error-page rails-env-production'>
<div class='container'>
<nav class='site-header'>
<a class='logo float-left' href='/' id='pivotal_cf_logo'>
<div class='pivotal-logo'></div>
<div class='operations-manager-logo'></div>
</a>
</nav>
<section class='content-container twelve columns'>
<div class='error'>
<h1>500 An error occurred.</h1>
<h2>Contact Pivotal Technical Support to report the problem.</h2>

<p><a href="/">Back to dashboard</a></p>
<hr>
<pre>NoMethodError</pre>
<pre>undefined method `permit' for nil:NilClass</pre>
<pre>/home/tempest-web/tempest/web/app/models/use_cases/director_configuration_updater.rb:54:in `valid_params'
/home/tempest-web/tempest/web/app/models/use_cases/director_configuration_updater.rb:6:in `initialize'
/home/tempest-web/tempest/web/app/controllers/infrastructure/director_configurations_controller.rb:13:in `new'
/home/tempest-web/tempest/web/app/controllers/infrastructure/director_configurations_controller.rb:13:in `update'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:22:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'
/home/tempest-web/tempest/web/lib/rack/streaming.rb:63:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'</pre>
<hr>
<p class='footer'><a href="/">Back to dashboard</a></p>
</div>
</section>
<footer class='site-footer'>
<span class='version'>PCF Ops Manager v1.10.1.0;</span>
<span>&copy;2013-2017 Pivotal Software, Inc; All Rights Reserved.</span>
<span class='float-right'><a href="/eula">End User License Agreement</a></span>
<span class='float-right'>&nbsp;|&nbsp;</span>
<span class='float-right'><a href="/docs">API Docs</a></span>
</footer>

</div>
</body>
</html>

0
```

**Comment by rizwanreza** [comment]
This issue should be opened against [OpsManager](https://github.com/pivotal-cf/installation). Om is a lightweight CLI client for OpsManager API, and unsetting the `director_hostname` needs to be supported at the API level.

**Comment by rizwanreza** [comment]
Do you still get the same error when setting `director_hostname` to `null`?
