### ISSUE TITLE
--az-configuration on vSphere is broken

### ISSUE THREAD

**Issue by krishicks** [pivotal-cf/om#79]
When I use `--az-configuration` I get a 500 error.

This is the 500:

```
        Exception caught via rescue_from (code 500):
        (See app/controllers/application_controller.rb)
        missing keyword: name
    /home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone.rb:15:in `initialize'
/home/tempest-web/tempest/web/app/models/persistence/models/base_availability_zone.rb:11:in `new'
/home/tempest-web/tempest/web/app/models/persistence/models/base_availability_zone.rb:11:in `load_from_hash'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone_collection.rb:8:in `block in load_from_hash'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone_collection.rb:8:in `map'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone_collection.rb:8:in `load_from_hash'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_infrastructure.rb:71:in `build_availability_zone_collection'
/home/tempest-web/tempest/web/app/presenters/availability_zones_presenter.rb:20:in `load_availability_zones_from_params'
/home/tempest-web/tempest/web/app/presenters/availability_zones_presenter.rb:12:in `initialize'
/home/tempest-web/tempest/web/app/controllers/infrastructure/availability_zones_controller.rb:11:in `new'
/home/tempest-web/tempest/web/app/controllers/infrastructure/availability_zones_controller.rb:11:in `update'
```

This is the PUT data:
```
  Parameters: {"authenticity_token"=>"[FILTERED]", "availability_zones"=>{"availability_zones"=>[{"cluster"=>"A-Cluster"}, {"cluster"=>"B-Cluster"}, {"cluster"=>"C-Cluster", "name"=>"AZ 01"}, {"name"=>"AZ 02"}, {"name"=>"AZ 03", "resource_pool"=>"a-cluster-rp05"}, {"resource_pool"=>"b-cluster-rp05"}, {"resource_pool"=>"c-cluster-rp05"}]}}
```

That PUT data looks pretty broken to me.

The JSON that's given to `--az-configuration` is the following:

```
{
  "availability_zones": [
    {
      "name": "$AZ_1",
      "cluster": "$AZ_1_CLUSTER_NAME",
      "resource_pool": "$AZ_1_RP_NAME"
    },
    {
      "name": "$AZ_2",
      "cluster": "$AZ_2_CLUSTER_NAME",
      "resource_pool": "$AZ_2_RP_NAME"
    },
    {
      "name": "$AZ_3",
      "cluster": "$AZ_3_CLUSTER_NAME",
      "resource_pool": "$AZ_3_RP_NAME"
    }
  ]
}
```

**Comment by krishicks** [comment]
I've narrowed this down to a problem with how Golang encodes spaces, and how Ops Mgr handles those spaces.

See https://github.com/golang/go/issues/4013

Spaces in query params get encoded with a `+` rather than `%20`. This form is received by Ops Mgr and is utterly broken on the receiving end.

**Comment by joshzarrabi** [comment]
We ran the following command which has an AZ with a space and configured AZs successfully:
```
$ om -u username -p password -t pcf.url.com -k configure-bosh -a '{
  "availability_zones": [
    {
      "name": "first az",
      "cluster": "private",
      "resource_pool": "foo"
    }
  ]}
'
```
However, when we try to configure multiple azs (without spaces in name) in one command, we saw the same issue as @krishicks:

```
om -u username -p password -t pcf.url.com -k configure-bosh -a '{
  "availability_zones": [
    {
      "name": "first-az",
      "cluster": "private",
      "resource_pool": "foo"
    },
    {
      "name": "second-az",
      "cluster": "private",
      "resource_pool": "foo"
    },
    {
      "name": "third-az",
      "cluster": "private",
      "resource_pool": "foo"
    }
  ]}"
```

The exact stack trace we saw is 
```
<pre>ArgumentError</pre>
<pre>missing keyword: name</pre>
<pre>/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone.rb:15:in `initialize'
/home/tempest-web/tempest/web/app/models/persistence/models/base_availability_zone.rb:11:in `new'
/home/tempest-web/tempest/web/app/models/persistence/models/base_availability_zone.rb:11:in `load_from_hash'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone_collection.rb:8:in `block in load_from_hash'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone_collection.rb:8:in `map'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_availability_zone_collection.rb:8:in `load_from_hash'
/home/tempest-web/tempest/web/app/models/persistence/models/vsphere/vsphere_infrastructure.rb:71:in `build_availability_zone_collection'
/home/tempest-web/tempest/web/app/presenters/availability_zones_presenter.rb:20:in `load_availability_zones_from_params'
/home/tempest-web/tempest/web/app/presenters/availability_zones_presenter.rb:12:in `initialize'
/home/tempest-web/tempest/web/app/controllers/infrastructure/availability_zones_controller.rb:11:in `new'
/home/tempest-web/tempest/web/app/controllers/infrastructure/availability_zones_controller.rb:11:in `update'
```

After doing a little more research, we think that this is caused by the way om orders the form params in the request (https://github.com/pivotal-cf/om/blob/master/commands/configure_bosh.go#L115-L123).

**Comment by joshzarrabi** [comment]
We will need to dedicate a track of work to making `om` work for vsphere... For now it is still unsupported and it should not be used. We will update the docs accordingly. @krishicks @kkallday

**Comment by krishicks** [comment]
I'm surprised the existing test which asserts the form that is submitted is passing if that form, when submitted to a real OpsMgr, results in an error.

**Comment by kkallday** [comment]
Currently the test asserts the correctness of a form that has known to work
for configuring a single AZ. Eventually our work on vSphere support will
drive us to improve the test so that it resembles a form that is known to
work when configuring multiple AZs.

On Jun 22, 2017 7:05 PM, "krishicks" <notifications@github.com> wrote:

I'm surprised the existing test which asserts the form that is submitted is
passing if that form, when submitted to a real OpsMgr, results in an error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pivotal-cf/om/issues/79#issuecomment-310550667>, or mute
the thread
