### ISSUE TITLE
Error for configure-bosh on aws

### ISSUE THREAD

**Issue by emperorente** [pivotal-cf/om#80]
opsmgr version:1.10.9
seems like opsman's problem, when I execute the om with the params separately like:

1.om --target https://x.x.x.x --skip-ssl-validation --username test --password 'test' configure-bosh --Iaas-configuration '{ data
}', It response "configuring Iaas specific options for Bosh tile
finished configuring Bosh tile", sounds like success, but opsman didn't save the params,

2.om --target https://x.x.x.x --skip-ssl-validation --username test --password 'test' configure-bosh
--Iaas-configuration --director-configuration --az-configuration, it response
"Configuring Iaas specific options for Bosh tile
configuring director options for Bosh tile
configuring availability zones for Bosh tile
could not execute "configure-bosh": could not fetch form: could not find the form authenticity token"

3.when I use the "configure-director" pipelines shows params from "pcf-pipelines" fill in the opsman manually, everything is ok.

so maybe the new version of opsmgr change itself's api response or the om's problem??

**Comment by davewalter** [comment]
Hi @emperorente,

We're currently looking into the first issue you mentioned above. It was also reported in issue #82 so you might want to review that for any helpful information/advise.

Regarding the second issue, that is something we just noticed where `om` doesn't give you the most helpful error message. We suspect that the problem there is that your IAAS configuration is incomplete, and Ops Manager is preventing you from attempting to configure the AZs until that form has been completed. We will be improving the error message returned in a future version of `om`.

Regards,
Dave

**Comment by davewalter** [comment]
Hi @emperorente,

We think we've found the root cause. For some reason, Ops Manager will respond with `200 OK` if there are missing required fields in the request payload, instead of the expected `422 Unprocessable Entity`. 

Please confirm that you are specifying all required properties in your payloads and let me know if this fixes your issue.

Regards,
Dave

**Comment by davewalter** [comment]
Hi @emperorente,

Just checking in to see if you had found the issue with your configuration so that we could close this issue?

Regards,
Dave

**Comment by emperorente** [comment]
hi, I'll confirm it today

**Comment by madamkiwi** [comment]
Hello @emperorente Just checking in if you'd like us to further investigate this issue or if it's already resolved from your side.  Please let us know.  Thanks!

**Comment by madamkiwi** [comment]
Closing for now.  Please feel free to reopen if you'd like us to further investigate.

**Comment by emperorente** [comment]
sorry for so late, i try it this morning, and the error info as follows:
could not execute "configure-bosh": tile failed to configure: request failed: unexpected response:
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Mon, 24 Jul 2017 23:07:41 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Set-Cookie: _web_session=ZDE0MG1pdXo2SktWM3dwMTMxVVpwNUhlZUFaWVZtelpzS2w1UHpnT1QvWHBJaHZ1TEszNThLTnFmVWhSRE40RThQejRrZlRHeHNtbEhzRERyS2p4Nk43aXdGTFV3cXJzYXB2N0FjVUhQUHdFQ3NZS3luQTdOMDQ3NjNYKzRKakZYdUVvOEgrdlMzaktBMHArTzQySmpBPT0tLUFOZ2FPLys4TFFZOWlDUDhRV3dUSFE9PQ%3D%3D--f258dddb6cfb5e893d6f8e4b23bcbabe55262359; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: ab0ba59b-e1df-47e3-bb54-43f6d43b6946
X-Runtime: 0.115740
X-Xss-Protection: 1; mode=block

31af
<!DOCTYPE html>
<html>
<head>
<meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
<meta content='0' http-equiv='expires'>
<meta content='text/javascript' http-equiv='Content-Script-Type'>
<meta content='text/css' http-equiv='Content-Style-Type'>
<meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
<link href='/favicon.png' rel='icon' type='image/png'>
<title>Ops Manager</title>
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="Nf7/4AI108NUdt6g9m+E2L9JdusQ/p8UnEsX98fLAxwks6aAarg5i9vm6oL0Oe2bD66YA8X8Zb6V2DU99bAwHA==" />
<link rel="stylesheet" media="screen" href="/assets/application-2c29ca884d37864467d5334e1c4883aa2e3c58c564e77a00d4c3b12fe66bb4b0.css" />
<script src="/assets/application-3f515a698587bf8a738bf1f5f944a2c08fed10676595d017d6de9b2eb2cbd9fb.js"></script>


</head>
<body class='error-page rails-env-production'>
<div class='container'>
<nav class='site-header'>
<a class='logo float-left' href='/' id='pivotal_cf_logo'>
<div class='pivotal-logo'></div>
<div class='operations-manager-logo'></div>
</a>
</nav>
<section class='content-container twelve columns'>
<div class='error'>
<h1>500 An error occurred.</h1>
<h2>Contact Pivotal Technical Support to report the problem.</h2>

<p><a href="/">Back to dashboard</a></p>
<hr>
<pre>NoMethodError</pre>
<pre>undefined method `cpu' for nil:NilClass</pre>
<pre>/home/tempest-web/tempest/web/app/models/persistence/models/job.rb:393:in `assign_primitive_resources!'
/home/tempest-web/tempest/web/app/models/persistence/models/job.rb:87:in `block in &lt;class:Job&gt;'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:338:in `valid?'
/home/tempest-web/tempest/web/app/models/persistence/models/product.rb:143:in `map'
/home/tempest-web/tempest/web/app/models/persistence/models/product.rb:143:in `jobs_valid?'
/home/tempest-web/tempest/web/app/presenters/product_resources_presenter.rb:35:in `apply'
/home/tempest-web/tempest/web/app/controllers/infrastructure/director/resources_controller.rb:16:in `update'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:22:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'
/home/tempest-web/tempest/web/lib/rack/streaming.rb:63:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'</pre>
<hr>
<p class='footer'><a href="/">Back to dashboard</a></p>
</div>
</section>
<footer class='site-footer'>
<span class='version'>PCF Ops Manager v1.10.12.0;</span>
<span>&copy;2013-2017 Pivotal Software, Inc; All Rights Reserved.</span>
<span class='float-right'><a href="/eula">End User License Agreement</a></span>
<span class='float-right'>&nbsp;|&nbsp;</span>
<span class='float-right'><a href="/docs">API Docs</a></span>
</footer>

</div>
</body>
</html>

0

**Comment by emperorente** [comment]
HI, could you pls give me a remote support when you guys got some times?

**Comment by ryanmoran** [comment]
@emperorente without knowing what you specified for the `configure-bosh` command, we cannot really provide much insight. This error is indicating that some unknown property is being specified. Can you provide us with your configuration JSON?

**Comment by emperorente** [comment]
I remove all the sensitive information, and info as follows:


om --target https://myurl \
  --skip-ssl-validation \
  --username tw-toc \
  --password password \
  configure-bosh \
  --iaas-configuration '{
  "access_key_id": "mykeyid",
  "secret_access_key": "mykey",
  "vpc_id": "vpc-ed86e994",
  "security_group": "sg-05d3e474",
  "key_pair_name": "PCF",
  "ssh_private_key": "mykey",
  "region": "us-east-1",
  "encrypted": false }' \
  --director-configuration '{
  "ntp_servers_string": "0.amazon.pool.ntp.org,1.amazon.pool.ntp.org,2.amazon.pool.ntp.org,3.amazon.pool.ntp.org",
  "resurrector_enabled": true,
  "max_threads": 30,
  "database_type": "external",
  "external_database_options": {
    "host": "toc-sandbox-pcf.cimcozvyfv1j.us-east-1.rds.amazonaws.com",
    "port": 3306,
    "user": "bosh",
    "password": "mypwd",
    "database": "mydb"
  },
  "blobstore_type": "s3",
  "s3_blobstore_options": {
    "endpoint": "https://s3.amazonaws.com",
    "bucket_name": "toc-sandbox-pcf-bosh",
    "access_key": "mykey",
    "secret_key": "mykey",
    "signature_version": "2",
    "region": "us-east-1"
  }
}' \
--az-configuration '{
"availability_zones": [
    {"name": "us-east-1a"},
    {"name": "us-east-1b"},
    {"name": "us-east-1d"}
  ]
}' \
--networks-configuration '{
"icmp_checks_enabled": false,
  "networks": [
    {
      "name": "deployment",
      "service_network": false,
      "subnets": [
        {
          "iaas_identifier": "subnet-c525bfe9",
          "cidr": "192.168.16.0/20",
          "reserved_ip_ranges": "192.168.16.0 - 192.168.16.10",
          "dns": "192.168.0.2",
          "gateway": "192.168.16.1",
          "availability_zones": [
            "us-east-1a"
          ]
        },
        {
          "iaas_identifier": "subnet-d3df839b",
          "cidr": "192.168.32.0/20",
          "reserved_ip_ranges": "192.168.32.0 - 192.168.32.10",
          "dns": "192.168.0.2",
          "gateway": "192.168.32.1",
          "availability_zones": [
            "us-east-1b"
          ]
        },
        {
          "iaas_identifier": "subnet-4540af21",
          "cidr": "192.168.48.0/20",
          "reserved_ip_ranges": "192.168.48.0 - 192.168.48.10",
          "dns": "192.168.0.2",
          "gateway": "192.168.48.1",
          "availability_zones": [
            "us-east-1d"
          ]
        }
      ]
    },
    {
      "name": "infrastructure",
      "service_network": false,
      "subnets": [
        {
          "iaas_identifier": "subnet-c425bfe8",
          "cidr": "192.168.6.0/24",
          "reserved_ip_ranges": "192.168.6.0 - 192.168.6.10",
          "dns": "192.168.0.2",
          "gateway": "192.168.6.1",
          "availability_zones": [
            "us-east-1a"
          ]
        }
      ]
    },
    {
      "name": "services",
      "service_network": false,
      "subnets": [
        {
          "iaas_identifier": "subnet-a726bc8b",
          "cidr": "192.168.64.0/20",
          "reserved_ip_ranges": "192.168.64.0 - 192.168.64.10",
          "dns": "192.168.0.2",
          "gateway": "192.168.64.1",
          "availability_zones": [
            "us-east-1a"
          ]
        },
        {
          "iaas_identifier": "subnet-27d8846f",
          "cidr": "192.168.80.0/20",
          "reserved_ip_ranges": "192.168.80.0 - 192.168.80.10",
          "dns": "192.168.0.2",
          "gateway": "192.168.80.1",
          "availability_zones": [
            "us-east-1b"
          ]
        },
        {
          "iaas_identifier": "subnet-c644aba2",
          "cidr": "192.168.96.0/20",
          "reserved_ip_ranges": "192.168.96.0 - 192.168.96.10",
          "dns": "192.168.0.2",
          "gateway": "192.168.96.1",
          "availability_zones": [
            "us-east-1d"
          ]
        }
      ]
    }
  ]
}' \
--network-assignment '{ 
  "singleton_availability_zone": "us-east-1a",
  "network": "infrastructure"
}' \
--security-configuration '{
  "trusted_certificates": "",
  "vm_password_type": "generate"
}' \
--resource-configuration '{
    "director": {
    "instance_type": {
    "id": "m4.large"
     }
  }
}'

**Comment by emperorente** [comment]
and I use the opsmgr version 1.11.5, update the error info:
in pcf-pipelines :
![image](https://user-images.githubusercontent.com/15973223/28646936-dcbe7fac-7296-11e7-85a8-9a6d7b9aa4dd.png)
when use om cli:
configuring iaas specific options for bosh tile
configuring director options for bosh tile
could not execute "configure-bosh": tile failed to configure: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Wed, 26 Jul 2017 16:41:06 GMT
Server: nginx/1.4.6 (Ubuntu)
Set-Cookie: _web_session=aEFQQjB5Uk1NcWNBRUNkcUFYY0VBZm9oaE92MDUwR2pYY1Z3Ty9YSXJlZXNsa3BLbzVueEpkZHNnZ0loSndZUHh4N0IwVjZzcGY2cVFJVjhXS1E4SVNEZFh1MEIrZzdxL2JIVmp2aU84QlYrbzRITWl1SkRkMHJsamIvam1jR0JVbUEyNUN2bHphSlVBenJTOTRUQndBPT0tLUxWdjFtRy9wL292Q3FrL2dJbWkxSVE9PQ%3D%3D--e819a45687995463eacb158444e7839125ebbeb0; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 7a7a1a49-279a-42de-92fe-65e338b67082
X-Runtime: 0.452129
X-Xss-Protection: 1; mode=block

**Comment by kkallday** [comment]
Hi @emperorente,

That error normally occurs if authentication hasn't been setup on the ops manager. When you go to the Ops Manager Dashboard does it ask for you to configure authentication?

**Comment by emperorente** [comment]
@kkallday, when I log into the Dashboard, it requires me fill in the user & password,
![image](https://user-images.githubusercontent.com/15973223/29058322-575fe8cc-7c42-11e7-9814-e898b10c8f90.png)

**Comment by emperorente** [comment]
@kkallday when I open the dashboard, it requires me fill in the user & passwd 
![image](https://user-images.githubusercontent.com/15973223/29058370-8ed20f24-7c42-11e7-872b-94ac4984673c.png)
